var BirthdayMagic = require("./birthday-magic");
var BirthdayMagicObj = new BirthdayMagic(08, 09, 2013);

var planet = BirthdayMagicObj.planet();
console.log("planet type : " + typeof planet);
console.log(planet);
var gemstone = BirthdayMagicObj.gemstone();
console.log("gemstone type : " + typeof gemstone);
console.log(gemstone);
var sign = BirthdayMagicObj.sign();
console.log("sign type : " + typeof sign);
console.log(sign);
var flower = BirthdayMagicObj.flower();
console.log("flower type : " + typeof flower);
console.log(flower);
var all = BirthdayMagicObj.all();
console.log("all type : " + typeof all);
console.log(all);
var allFlower= BirthdayMagicObj.all().flower;
console.log("allFlower type : " + (allFlower instanceof Array ? 'Array' : typeof allFlower));
console.log(allFlower);